spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8889/aec-blogs
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true

